version: "3.9"

services:
  backend:
    image: aryasingh55/educart-backend:latest
    ports:
      - "5002:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: aryasingh55/educart-frontend:latest
    ports:
      - "3002:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
