version: "3.8"

services:
  backend:
    image: aryasingh55/educart-backend
    ports:
      - "5000:5000"  # host:container
    deploy:
      placement:
        constraints: [node.role == manager]

  frontend:
    image: aryasingh55/educart-frontend
    ports:
      - "3000:80"  # host:container
    depends_on:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
