version: "3.8"

services:
  backend:
    image: aryasingh55/educart-backend
    ports:
      - "5000:5000"  # Expose backend on port 5000
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  frontend:
    image: aryasingh55/educart-frontend
    ports:
      - "3000:80"  # Expose frontend on port 3000
    depends_on:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
