services:
  backend:
    image: aryasingh55/educart-backend
    ports:
      - "5000:5000"
    

  frontend:
    image: aryasingh55/educart-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    